number_1 = input ("Please enter the first number: ")
number_2 = input ("Please enter the second number: ")
result = int(number_1) + int(number_2)
print (number_1 + " + " + number_2 + " = "+ str(result))
print (f"{number_1} + {number_2} = {result}")